import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import { EmotionCacheProvider } from '@/components/providers/EmotionCacheProvider'
import { CrafterAppProvider } from '@/components/providers/CrafterAppProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const siteName = process.env.NEXT_PUBLIC_CRAFTERCMS_SITE_NAME;
if (typeof siteName === 'undefined') {
  throw new Error('The value of `NEXT_PUBLIC_CRAFTERCMS_SITE_NAME` is not defined. Did you create a `.env` file and declare the `NEXT_PUBLIC_CRAFTERCMS_SITE_NAME` variable?');
} else if (siteName === '') {
  throw new Error('The site name value of is blank. Set `NEXT_PUBLIC_CRAFTERCMS_SITE_NAME=YOUR_SITE_NAME` in your .env file.');
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <EmotionCacheProvider>
      <CrafterAppProvider>
        <html lang="en">
          <body className={inter.className}>{children}</body>
        </html>
      </CrafterAppProvider >
    </EmotionCacheProvider>
  )
}
