# testing server

GET https://craftercms-auth.tekcent.com/api/1/site/content_store/tree.json?url=/site/website/&site=next-js

###
# testing server get up to 3 levels of child nodes

GET https://craftercms-auth.tekcent.com/api/1/services/get-pages.json?path=/site/website/pressrelease&depth=3

###
# localhost docker server

GET http://localhost:8080/api/1/site/content_store/tree.json?url=/site/website&site=nbp


###
GET http://localhost:8080/api/1/services/page.json?path=/site/website&depth=3&crafterSite=nbp
